apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-kubernetes-deployment
  labels:
    app: dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet
        image: mikber/dotnetapp
        ports:
        - containerPort: 8080