apiVersion: v1 
kind: Service
metadata:
  name: devops-project-kubernetes-service
  labels:
    app: dotnet-app
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
  - port: 8080
    targetPort: http